Specified python 3.6 minor version
Due to error in workflow https://github.com/mozilla-services/shavar-prod-lists/actions/runs/6774247958/job/18410898304?pr=603

Error: Version 3.6 with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json